fix makefile

diff --git a/tests/muscle3/actors/cpp/basic_cpp/Makefile b/tests/muscle3/actors/cpp/basic_cpp/Makefile
--- a/tests/muscle3/actors/cpp/basic_cpp/Makefile
+++ b/tests/muscle3/actors/cpp/basic_cpp/Makefile
@@ -6,11 +6,11 @@ CODE_LANGUAGE=cpp
 WRAPPED_CODE_NAME=basic
 
 clean wrapped actor actor-gui wf-run check-output test:
-@if [ -z "$(TESTS_DIR)" ]; then \
-	echo "Error: TESTS_DIR is not set"; \
-	exit 1; \
-fi
-@echo "TESTS_DIR: $(TESTS_DIR)"
+	@if [ -z "$(TESTS_DIR)" ]; then \
+		echo "Error: TESTS_DIR is not set"; \
+		exit 1; \
+	fi
+	@echo "TESTS_DIR: $(TESTS_DIR)"
 
 @if [ ! -f "$(TESTS_DIR)/Makefile" ]; then \
 	echo "Error: $(TESTS_DIR)/Makefile not found"; \
